// 服务器数据
const serverList = [
    {
        id: 1,
        name: "[Starvm] HK CN2 VPS",
        vendor: "Starvm",
        type: "VPS",
        memory: "4C4G-30GB",
        bandwidth: "20Mbps",
        price: "￥28/月",
        monthlyCost: 28,
        expire: "2026-01-07",
        status: "normal",
    },
    {
        id: 2,
        name: "[Azure] Singapore VPS",
        vendor: "Azure",
        type: "VPS",
        memory: "2C1G-60GB",
        bandwidth: "2.5Gbps",
        price: "$21/年",
        monthlyCost: 12.34,
        expire: "2026-09-14",
        status: "normal",
    },
    {
        id: 3,
        name: "[Sadidc] HK happy-Lv2",
        vendor: "Sadidc",
        type: "VPS",
        memory: "2C2G-40GB",
        bandwidth: "20Mbps",
        price: "￥14/月",
        monthlyCost: 14,
        expire: "2026-01-08",
        status: "normal",
    },
    {
        id: 4,
        name: "[Sadidc] Sad-us plus CN2",
        vendor: "Sadidc",
        type: "VPS",
        memory: "8C8G-100GB",
        bandwidth: "100Mbps",
        price: "￥24.99/月",
        monthlyCost: 24.99,
        expire: "2026-01-06",
        status: "normal",
    },
    {
        id: 5,
        name: "[Sadidc] HKbig Sad plus",
        vendor: "Sadidc",
        type: "VPS",
        memory: "8C8G-100GB",
        bandwidth: "50Mbps",
        price: "￥27/月",
        monthlyCost: 27,
        expire: "2025-12-22",
        status: "normal",
    },
    {
        id: 6,
        name: "[Sadidc] Zaozhuang sleep A",
        vendor: "Sadidc",
        type: "Idle Treasure",
        memory: "1C1G-30GB",
        bandwidth: "10Mbps",
        price: "￥1/月",
        monthlyCost: 1,
        expire: "2025-12-22",
        status: "normal",
    },
    {
        id: 7,
        name: "[Sadidc] HK-A tiny",
        vendor: "Sadidc",
        type: "LXC Mini-Computer",
        memory: "1C128M-1GB",
        bandwidth: "150Mbps",
        price: "￥12/年",
        monthlyCost: 1,
        expire: "2026-11-08",
        status: "normal",
    },
];

// 服务器状态映射
const serverStatus = {
    'sold': { text: '已售', class: 'badge-sold', footerClass: '' },
    'normal': { text: '正常', class: 'badge-normal', footerClass: 'footer-normal' }
};
